# Generated by Django 5.2.4 on 2025-08-25 15:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.AddField(
            model_name='review',
            name='stars',
            field=models.PositiveBigIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0, 'Avaliação não pode ser inferior a 0 estrelas.'), django.core.validators.MaxValueValidator(5, 'Avaliação não pode ser superior a 5 estrelas.')]),
            preserve_default=False,
        ),
    ]
