# Generated by Django 5.2.4 on 2025-07-10 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('bio', models.TextField(blank=True, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(choices=[('American', 'American'), ('British', 'British'), ('Canadian', 'Canadian'), ('Australian', 'Australian'), ('Indian', 'Indian'), ('Other', 'Other')], default='Other', max_length=50)),
            ],
        ),
    ]
